name: PR Testing

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-pull-request-actions:
    name: Reusable Crypto3 Testing
    uses: ./.github/workflows/pull-request-action.yml

    secrets: inherit
    with:
      targets: |
          marshalling_fri_commitment_test
          marshalling_lpc_commitment_test
          marshalling_placeholder_common_data_test
          marshalling_placeholder_proof_test
          marshalling_sparse_vector_test
          marshalling_accumulation_vector_test
          marshalling_plonk_constraint_system_test
          marshalling_plonk_assignment_table_test
          marshalling_plonk_gates_test
          marshalling_r1cs_gg_ppzksnark_primary_input_test
          marshalling_r1cs_gg_ppzksnark_proof_test
          marshalling_r1cs_gg_ppzksnark_verification_key_test

#         Test should be fixed
#          marshalling_merkle_proof_test
